#Dockerfile for Taisun dyndns updater
#2017
#Use alpine base image
FROM alpine:3.8

MAINTAINER Ryan Kuba <ryankuba@gmail.com>

# Install dependencies
RUN apk add --no-cache --update curl 

# Add loop for pinging Taisun
COPY ./pingtaisun.sh /pingtaisun.sh

RUN chmod +x /pingtaisun.sh

CMD ["/bin/sh", "/pingtaisun.sh"]
