#Dockerfile for Taisun dyndns updater
#2017
#Use alpine base image
FROM alpine@sha256:78f3ccd48cc6a55709b65c8fdb3ef81ed922c5393b064d63b0d35f51e0c9fb2e

MAINTAINER Ryan Kuba <ryankuba@gmail.com>

# Add qemu to build on x86_64 systems
COPY qemu-arm-static /usr/bin

# Install dependencies
RUN apk add --no-cache --update curl 

# Add loop for pinging Taisun
COPY ./pingtaisun.sh /pingtaisun.sh

RUN chmod +x /pingtaisun.sh

CMD ["/bin/sh", "/pingtaisun.sh"]
